name: Fetch Codeforces and Codechef Submissions

on:
  schedule:
    - cron: '0 0 * * *'  # Runs once a day at midnight
  workflow_dispatch:  # Allows manual trigger

jobs:
  fetch_submissions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Codeforces sync script
        run: |
          python sync_codeforces.py  # Runs the renamed Codeforces script

      - name: Run CodeChef sync script
        run: |
          python sync_codechef.py  # Runs the renamed CodeChef script

      - name: Commit and push changes
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your-email@example.com"
          git add .
          git commit -m "Update submissions"
          git push
